[package]
name = "fpgrars"
version = "1.13.1"
authors = ["Leonardo Riether <leonardoalves8217@gmail.com>"]
edition = "2018"

[features]
show_ms = [] # show ms per frame in the window title
8-bit-display = [] # 8-bit color format for the bitmap display

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[build-dependencies]
clap = "2.33.3"
version_check = "0.9"

[dependencies]
lazy_static = "1.4.0"
rand = "0.7.3"

pixel-canvas = "0.2.2"
glium = "0.28.0"

nom = "5.1.2"

radix_trie = "0.0.9"
fnv = "1.0.7"

byteorder = "1.3.4"

midir = "0.7.0"

[dependencies.clap]
version = "2.33.3"
features = ["suggestions", "color", "wrap_help"]

