site_name: FPGRARS
site_url: https://leoriether.github.io/fpgrars/
extra_css: [style/extra.css]
theme:
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - content.code.copy
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
